name: CI/CD

on:
  push:
     branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ruff-linter:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install uv
        run: pip install uv

      - name: install ruff
        run: uv sync --frozen

      - name: check code quality
        run: uv run ruff check .

      - name: check code format
        run: uv run ruff format --check


  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: install uv
        run: pip install uv

      - name: install project dependencies
        run: uv sync --frozen

      - name: run tests
        run: uv run pytest
